# Generated by Django 4.0.5 on 2022-06-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=10, verbose_name='Fecha')),
                ('IDCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tien.clientes', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=80, verbose_name='Precio')),
                ('IDCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tien.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=50, verbose_name='Cantidad')),
                ('IDFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tien.factura', verbose_name='Factura')),
                ('IDProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tien.producto', verbose_name='Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='IDProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tien.proveedor', verbose_name='Proveedor'),
        ),
    ]
